name: VRChat
main: base.plugin.ChatHandler
version: 1.2.8
commands:
    vrchat:
        description: Generic VRChat command.
    ooc:
        description: Changes chat to the global (out-of-character) chat channel
    say:
        description: Changes chat to the local (8 blocks) chat channel
    yell:
        description: Changes chat to the local (256 blocks) chat channel
    whisper:
        description: Changes chat to the local (2 blocks) chat channel
    emote:
        description: Sends a local emote
    s:
        description: Alias for say
    y:
        description: Alias for yell
    w:
        description: Alias for whisper
    e:
        description: Alias for emote